#!/usr/bin/env python3

import argparse
import logging
import os
import time
import backoff
import requests

from dotenv import load_dotenv

logging.basicConfig(
    filename="../logs/midjourney_api.log",
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

# Load environment variables
load_dotenv()


class MidjourneyAPI:
    def __init__(self):
        self.authorization = os.getenv('MIDJOURNEY_AUTH')
        self.application_id = os.getenv('MIDJOURNEY_APPLICATION_ID')
        self.guild_id = os.getenv('MIDJOURNEY_GUILD_ID')
        self.channel_id = os.getenv('MIDJOURNEY_CHANNEL_ID')
        self.session_id = os.getenv('MIDJOURNEY_SESSION_ID')
        self.data_version = os.getenv('MIDJOURNEY_DATA_VERSION')
        self.data_id = os.getenv('MIDJOURNEY_DATA_ID')
        self.download_queue = 0
        self.logger = logging.getLogger(__name__)

    def imagine(self, prompt):
        """
        Sends a prompt to the Midjourney bot to generate an image.

        Args:
            prompt (str): The prompt to send to the bot.

        Returns:
            requests.models.Response: The response from the API.
        """
        try:
            return requests.post(
                "https://discord.com/api/v9/interactions",
                headers={
                    "Authorization": self.authorization,
                    "Content-Type": "application/json",
                },
                json={
                    "type": 2,
                    "application_id": self.application_id,
                    "guild_id": self.guild_id,
                    "channel_id": self.channel_id,
                    "session_id": self.session_id,
                    "data": {
                        "version": self.data_version,
                        "id": self.data_id,
                        "name": "imagine",
                        "type": 1,
                        "options": [
                            {
                                "type": 3,
                                "name": "prompt",
                                "value": prompt
                            }
                        ],
                        "application_command": {
                            "id": self.data_id,
                            "type": 1,
                            "application_id": self.application_id,
                            "version": self.data_version,
                            "name": "imagine",
                            "description": "Create images with Midjourney",
                            "options": [
                                {
                                    "type": 3,
                                    "name": "prompt",
                                    "description": "The prompt to imagine",
                                    "required": True,
                                    "description_localized": "The prompt to imagine",
                                    "name_localized": "prompt"
                                }
                            ],
                            "dm_permission": True,
                            "contexts": [0, 1, 2],
                            "intregration_types": [0, 1],
                            "global_popularity_rank": 1,
                            "description_localized": "Create images with Midjourney",
                            "name_localized": "imagine"
                        },
                        "attachments": []
                    }
                }
            )
        except requests.exceptions.HTTPError as err:
            self.logger.info(err)

    @backoff.on_exception(backoff.expo, ValueError, max_time=300)
    def upscale_images(self, n=4):
        """
        Upscale a number of images from the last prompt generated by the Midjourney bot.
        This function uses an exponential backoff strategy to retry the request if an error occurs.

        Args:
            n (int): The number of images to upscale.
        """
        try:
            response = requests.get(
                f"https://discord.com/api/v9/channels/{self.channel_id}/messages?limit=1",
                headers={
                    "Authorization": self.authorization,
                    "Content-Type": "application/json",
                }
            )

            # Get the most recent message id
            messages = response.json()
            most_recent_message_id = messages[0]['id']

            # Get the custom_ids of n buttons to upscale the images
            components = messages[0]['components'][0]['components']
            buttons = [comp for comp in components if comp.get('label') in ['U1', 'U2', 'U3', 'U4']]
            custom_ids = [button['custom_id'] for button in buttons]

            # Raise an error if the image generation is not complete
            if not custom_ids or len(custom_ids) < n:
                raise ValueError("No custom_ids found, waiting for the image generation to complete.")

            # Set the download queue to n
            self.download_queue = n

            # Upscale the images
            for custom_id in custom_ids[:n][::-1]:
                requests.post(
                    "https://discord.com/api/v9/interactions",
                    headers={
                        "Authorization": self.authorization,
                        "Content-Type": "application/json",
                    },
                    json={
                        "type": 3,
                        "guild_id": self.guild_id,
                        "channel_id": self.channel_id,
                        "message_flags": 0,
                        "message_id": most_recent_message_id,
                        "application_id": self.application_id,
                        "session_id": "cannot be empty",
                        "data": {
                            "component_type": 2,
                            "custom_id": custom_id,
                        }
                    }
                )
        except requests.exceptions.HTTPError as err:
            self.logger.info(err)

    @backoff.on_exception(backoff.expo, ValueError, max_time=300)
    def download_images(self, dest_path):
        """
        Download all upscaled images from the last prompt generated by the Midjourney bot.

        Args:
            dest_path (str): The path to save the images to.
        """
        try:
            response = requests.get(
                f'https://discord.com/api/v9/channels/{self.channel_id}/messages?limit={self.download_queue}',
                headers={
                    'Authorization': self.authorization,
                    'Content-Type': 'application/json',
                }
            )

            # Get the image urls for the upscaled images
            messages = response.json()

            # If one of the messages has upscaling buttons, backoff
            components = [message['components'][0]['components'] for message in messages]
            for comp in components:
                buttons = [c for c in comp if c.get('label') in ['U1', 'U2', 'U3', 'U4']]
                if buttons:
                    raise ValueError("Upscaling buttons found, waiting for the images to be upscaled.")

            image_urls = [message['attachments'][0]['url'] for message in messages]

            # Get the corresponding prompt for the images
            prompt = messages[0]['content'].split("**")[1]

            # Create a name for the generated image based on the prompt
            base_name = prompt.replace(" ", "_").replace(",", "").replace(".", "") + ".png"

            # Download the images
            for i, image_url in enumerate(image_urls):
                image_response = requests.get(
                    image_url,
                    headers={
                        'Authorization': self.authorization,
                        'Content-Type': 'application/json',
                    }
                )

                image_name = base_name.replace(".png", f"_{i + 1}.png")
                image_path = os.path.join(os.curdir, dest_path, image_name)

                with open(image_path, "wb") as f:
                    f.write(image_response.content)
        except requests.exceptions.HTTPError as err:
            self.logger.info(err)


def main(args):
    # Example usage of the MidjourneyAPI class
    api = MidjourneyAPI()
    api.imagine(args.prompt)
    time.sleep(60)
    api.upscale_images()
    time.sleep(2)
    if not os.path.exists(args.dest):
        os.makedirs(args.dest)
    api.download_images(args.dest)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Generate images using Midjourney v6 through the Discord '
                                                 'Interactions API.')
    parser.add_argument('--prompt', default='', type=str,
                        help='instructions for the model to generate an image')
    parser.add_argument('--dest', default="images", type=str,
                        help='path to save the images to')

    arguments = parser.parse_args()
    main(arguments)
